server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youchat?serverTimezone=Asia/Shanghai&useUnicode=true&charaacterEncoding=utf8
    username: root
    password: 137911
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
